name: Actions Dependencies

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  submit-dependencies:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: jessehouwing/actions-dependency-submission@19481049f19a8b6d54adbde7c323de5184b8bab5 # v1.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
