name: Actions Dependencies

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions: {}

jobs:
  submit-dependencies:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: jessehouwing/actions-dependency-submission@d4ed9fd03b1c91e31a62d9a4095440128ec1316b # v1.0.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
